### Required variables to train <model_name> with <dataset_name> in PyTorch.

# Model parameters
model:
    # Model name to train. choices are "ResNet18", "VGG16", "DLA"
    name: "ResNet18"

# Data parameters
dataset:
    # Dataset name to classify. choices are "CIFAR10"
    name: "CIFAR10"

# Random seed for reproducibility
seed:

# Training parameters
training:
    # Number of epochs
    num_epochs: 200

    # Optimizer
    optimizer:
        # Optimizer name. Choices are: "sgd", "nesterov_sgd", "rmsprop", "adagrad",
        # or "adam"
        name: "sgd"
        # Initial learning rate
        learning_rate: 0.1
        # Momentum factor
        momentum: 0.9
        # Weight decay (L2 penalty)
        weight_decay: 0.0005

    # Scheduler
    scheduler:
        # Scheduler name. Choices are: "constant", "step", "multistep", "exponential",
        # or "cosine"
        name: "cosine"
        # Scheduler specific key word arguments
        kwargs:

    # Batch sizes
    batch_size:
        train: 128
        val: 100

    # Resume training from checkpoint
    resume:
        from_checkpoint: false
        checkpoint_dir:
